/**
 * Unifi Controller API spec
 *
 * Reverse engineered API for Ubiquiti Unifi Controller
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: github@container42.de
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.lambertland.kotlin.unifiapi.generated.model


import kotlinx.serialization.SerialName
import java.io.Serializable

/**
 * 
 *
 * @param username 
 * @param password 
 * @param token 
 * @param rememberMe 
 */

data class Login (

    @SerialName("username")
    val username: kotlin.String,

    @SerialName("password")
    val password: kotlin.String,

    @SerialName("token")
    val token: kotlin.String? = null,

    @SerialName("rememberMe")
    val rememberMe: kotlin.Boolean? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

