/**
 * Unifi Controller API spec
 *
 * Reverse engineered API for Ubiquiti Unifi Controller
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: github@container42.de
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.lambertland.kotlin.unifiapi.generated.model


import kotlinx.serialization.SerialName
import java.io.Serializable

/**
 * 
 *
 * @param uniqueId 
 * @param id 
 * @param deviceToken 
 * @param firstName 
 * @param lastName 
 * @param fullName 
 * @param email 
 * @param emailIsNull 
 * @param phone 
 * @param avatarRelativePath 
 * @param avatarRpath2 
 * @param status 
 * @param employeeNumber 
 * @param createTime 
 * @param username 
 * @param localAccountExist 
 * @param passwordRevision 
 * @param updateTime 
 * @param isOwner 
 * @param isSuperAdmin 
 * @param isMember 
 */

data class LoginResponse (

    @SerialName("unique_id")
    val uniqueId: kotlin.String,

    @SerialName("id")
    val id: kotlin.String,

    @SerialName("deviceToken")
    val deviceToken: kotlin.String,

    @SerialName("first_name")
    val firstName: kotlin.String? = null,

    @SerialName("last_name")
    val lastName: kotlin.String? = null,

    @SerialName("full_name")
    val fullName: kotlin.String? = null,

    @SerialName("email")
    val email: kotlin.String? = null,

    @SerialName("email_is_null")
    val emailIsNull: kotlin.String? = null,

    @SerialName("phone")
    val phone: kotlin.String? = null,

    @SerialName("avatar_relative_path")
    val avatarRelativePath: kotlin.String? = null,

    @SerialName("avatar_rpath2")
    val avatarRpath2: kotlin.String? = null,

    @SerialName("status")
    val status: kotlin.String? = null,

    @SerialName("employee_number")
    val employeeNumber: kotlin.String? = null,

    @SerialName("create_time")
    val createTime: kotlin.Int? = null,

    @SerialName("username")
    val username: kotlin.String? = null,

    @SerialName("local_account_exist")
    val localAccountExist: kotlin.Boolean? = null,

    @SerialName("password_revision")
    val passwordRevision: kotlin.Int? = null,

    @SerialName("update_time")
    val updateTime: kotlin.Int? = null,

    @SerialName("isOwner")
    val isOwner: kotlin.Boolean? = null,

    @SerialName("isSuperAdmin")
    val isSuperAdmin: kotlin.Boolean? = null,

    @SerialName("isMember")
    val isMember: kotlin.Boolean? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

