/**
 * Unifi Controller API spec
 *
 * Reverse engineered API for Ubiquiti Unifi Controller
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: github@container42.de
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.lambertland.kotlin.unifiapi.generated.model


import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param attrHiddenId 
 * @param attrNoDelete 
 * @param desc 
 * @param role 
 */

@kotlinx.serialization.Serializable
data class Site (

    @SerialName("_id")
    val _id: kotlin.String,

    @SerialName("name")
    val name: kotlin.String,

    @SerialName("attr_hidden_id")
    val attrHiddenId: kotlin.String? = null,

    @SerialName("attr_no_delete")
    val attrNoDelete: kotlin.Boolean? = null,

    @SerialName("desc")
    val desc: kotlin.String? = null,

    @SerialName("role")
    val role: kotlin.String? = null

)



