/**
 * Unifi Controller API spec
 *
 * Reverse engineered API for Ubiquiti Unifi Controller
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: github@container42.de
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.lambertland.kotlin.unifiapi.generated.model

import kotlinx.serialization.SerialName
import java.io.Serializable

/**
 * 
 *
 * @param `data` 
 * @param meta 
 */
@kotlinx.serialization.Serializable
data class WlanConfs (

    @SerialName("data")
    val `data`: kotlin.Array<WlanConf>,

    @SerialName("meta")
    val meta: Meta

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

