/**
 * Unifi Controller API spec
 *
 * Reverse engineered API for Ubiquiti Unifi Controller
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: github@container42.de
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.lambertland.kotlin.unifiapi.generated.model


import kotlinx.serialization.SerialName
import java.io.Serializable

/**
 * 
 *
 * @param id 
 * @param name 
 * @param siteId 
 */
@kotlinx.serialization.Serializable
data class WlanGroup (

    @SerialName("_id")
    val id: kotlin.String,

    @SerialName("name")
    val name: kotlin.String,

    @SerialName("site_id")
    val siteId: kotlin.String

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

